module.exports = {
    environment: process.env.NODE_ENV || 'development',
    port: process.env.PORT || 8000,
    api_key: process.env.API_KEY,
    turnstile_key: process.env.TURSNSTILE_KEY,
    coin_gecko_api_key: process.env.COIN_GECKO_API_KEY,
    appKey: process.env.TWITTER_APP_KEY,
    appSecret: process.env.TWITTER_APP_SECRET,
    accessToken: process.env.TWITTER_ACCESS_TOKEN,
    accessSecret: process.env.TWITTER_ACCESS_SECRET,
    bearerToken: process.env.TWITTER_BEARER_TOKEN,
    secApiKey: process.env.SEC_API_KEY,
    mailtrapToken: process.env.MAILTRAPTOKEN,
    mailtrapEndpoint: process.env.MAILTRAPENDPOINT,
    alphaVantApiKey: process.env.ALPHA_VANT_API_KEY,
    mailtrapToken: process.env.MAILTRAPTOKEN,
    mailTrapEndpoint: process.env.MAILTRAPENDPOINT,
    db: {
      username: process.env.DB_USERNAME,
      password: process.env.DB_PASSWORD,
      database: process.env.DB_DATABASE,
      host: process.env.DB_HOST,
    },
    jwtConfig: {
      secret: process.env.JWT_SECRET,
      expiresIn: process.env.JWT_EXPIRES_IN,
    },
  };
